#!/usr/bin/env node
// Runtime smoke test for the built Angular host app.
//
// Prerequisites: `npx ng build` and a static server on the build output,
// e.g. `python3 -m http.server 5399` inside dist/angular-host/browser.
// Drives the real UI: opens a toolbox category, drags a block onto the
// canvas and asserts that the Berry code preview updates.
import {chromium} from 'playwright-core';

const baseUrl = process.env.SMOKE_URL ?? 'http://localhost:5399/';
const browser = await chromium.launch({
  executablePath: process.env.HARNESS_CHROMIUM ?? '/opt/pw-browsers/chromium',
});
const page = await browser.newPage({viewport: {width: 1440, height: 900}});
const consoleLines = [];
page.on('console', (msg) => consoleLines.push(`[${msg.type()}] ${msg.text()}`));
page.on('pageerror', (err) => consoleLines.push(`[pageerror] ${err.message}`));

const problems = [];
const check = (condition, message) => {
  if (!condition) problems.push(message);
};

try {
  await page.goto(baseUrl, {waitUntil: 'networkidle'});

  // Blockly workspace and BlockBerry toolbox render inside Angular.
  await page.waitForSelector('.blocklySvg', {timeout: 20000});
  const categories = await page.locator('.blocklyToolboxCategory').count();
  check(categories >= 5, `expected BlockBerry toolbox categories, got ${categories}`);

  // Drag the first block of the first category onto the canvas.
  await page.locator('.blocklyToolboxCategory').first().click();
  await page.waitForSelector('.blocklyFlyout .blocklyDraggable', {timeout: 5000});
  const block = page.locator('.blocklyFlyout .blocklyDraggable').first();
  const from = await block.boundingBox();
  const canvas = await page.locator('.editor').boundingBox();
  await page.mouse.move(from.x + from.width / 2, from.y + from.height / 2);
  await page.mouse.down();
  await page.mouse.move(canvas.x + canvas.width / 2, canvas.y + canvas.height / 2, {steps: 12});
  await page.mouse.up();
  await page.waitForTimeout(800);

  const stats = await page.textContent('.stats');
  check(!stats?.startsWith('0 Blöcke'), `block count should be > 0, got "${stats}"`);
  const code = await page.textContent('.code');
  check(
    !!code && code.includes('Generated by BlockBerry'),
    `code preview should contain generated Berry code, got: ${code?.slice(0, 120)}`,
  );

  const mediaErrors = consoleLines.filter((line) => line.includes('blockly-media'));
  check(mediaErrors.length === 0, `blockly media failed to load: ${mediaErrors.join(' | ')}`);
  const pageErrors = consoleLines.filter((line) => line.startsWith('[pageerror]'));
  check(pageErrors.length === 0, `page errors: ${pageErrors.join(' | ')}`);
} catch (error) {
  problems.push(`smoke run failed: ${error.message}`);
}

if (problems.length) {
  console.error(`✗ angular-host smoke\n  ${problems.join('\n  ')}`);
  console.error(consoleLines.join('\n'));
} else {
  console.log('✓ angular-host smoke: render, toolbox, drag block, generate code');
}

await browser.close();
process.exit(problems.length ? 1 : 0);
