import type {Block} from 'blockly/core';
import * as Blockly from 'blockly/core';
import {LuaGenerator} from 'blockly/lua';

/** Berry operator precedence. Lower values bind more tightly in Blockly. */
export enum BerryOrder {
  ATOMIC = 0,
  MEMBER = 1,
  UNARY = 2,
  MULTIPLICATIVE = 3,
  ADDITIVE = 4,
  RELATIONAL = 5,
  AND = 6,
  OR = 7,
  NONE = 99,
}

const RESERVED_WORDS =
  'and,as,break,class,continue,def,elif,else,end,false,for,if,import,nil,not,or,raise,return,static,true,var,while';

function value(
  generator: BerryGenerator,
  block: Block,
  input: string,
  fallback = 'nil',
  order = BerryOrder.NONE,
): string {
  return generator.valueToCode(block, input, order) || fallback;
}

function body(generator: BerryGenerator, block: Block, input: string): string {
  return generator.statementToCode(block, input) || `${generator.INDENT}nil\n`;
}

function identifier(input: string, fallback: string): string {
  const clean = input
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Za-z0-9_]/g, '_')
    .replace(/^([0-9])/, '_$1')
    .replace(/_+/g, '_');
  const candidate = clean || fallback;
  return RESERVED_WORDS.split(',').includes(candidate) ? `${candidate}_` : candidate;
}

function odIndex(input: unknown): string {
  const text = String(input).trim();
  if (/^0x[0-9a-f]{1,4}$/i.test(text)) return `0x${text.slice(2).toUpperCase()}`;
  if (/^\d+$/.test(text)) {
    const parsed = Number(text);
    if (parsed >= 0 && parsed <= 0xffff) return String(parsed);
  }
  return '0';
}

function numberField(block: Block, name: string, fallback = 0): number {
  const parsed = Number(block.getFieldValue(name));
  return Number.isFinite(parsed) ? parsed : fallback;
}

/**
 * Blockly generator for Berry.
 *
 * It reuses Blockly's Lua generator lifecycle as a compact base, but replaces
 * the emitted syntax and only exposes the standard blocks that have an explicit
 * Berry implementation.
 */
export class BerryGenerator extends LuaGenerator {
  constructor() {
    super('Berry');
    this.INDENT = '  ';
    this.addReservedWords(RESERVED_WORDS);
    this.installCoreGenerators();
    this.installDomainGenerators();
  }

  override init(workspace: Blockly.Workspace): void {
    this.nameDB_ ??= new Blockly.Names(RESERVED_WORDS);
    this.nameDB_.reset();
    this.nameDB_.setVariableMap(workspace.getVariableMap());
    this.nameDB_.populateVariables(workspace);
    this.nameDB_.populateProcedures(workspace);
    this.definitions_ = Object.create(null) as Record<string, string>;
    this.functionNames_ = Object.create(null) as Record<string, string>;

    const variables = workspace
      .getVariableMap()
      .getAllVariables()
      .map((model) => `var ${this.getVariableName(model.getId())} = nil`)
      .join('\n');
    if (variables) this.definitions_.variables = variables;
    this.isInitialized = true;
  }

  override finish(code: string): string {
    const definitions = Object.values(this.definitions_);
    const sections = ['# Generated by BlockBerry', ...definitions, code.trimEnd()].filter(Boolean);
    this.nameDB_?.reset();
    this.isInitialized = false;
    return `${sections.join('\n\n')}\n`;
  }

  override quote_(text: string): string {
    return JSON.stringify(text)
      .replace(/\u2028/g, '\\u2028')
      .replace(/\u2029/g, '\\u2029');
  }

  override scrubNakedValue(line: string): string {
    return `${line}\n`;
  }

  override scrub_(block: Block, code: string, thisOnly = false): string {
    const comment = block
      .getCommentText()
      ?.split('\n')
      .map((line) => `# ${line}\n`)
      .join('');
    const next = !thisOnly && block.nextConnection?.targetBlock();
    const nextCode = next ? this.blockToCode(next) : '';
    return `${comment ?? ''}${code}${typeof nextCode === 'string' ? nextCode : nextCode[0]}`;
  }

  private installCoreGenerators(): void {
    this.forBlock.logic_boolean = (block) => [
      block.getFieldValue('BOOL') === 'TRUE' ? 'true' : 'false',
      BerryOrder.ATOMIC,
    ];
    this.forBlock.logic_null = () => ['nil', BerryOrder.ATOMIC];
    this.forBlock.math_number = (block) => {
      const parsed = Number(block.getFieldValue('NUM'));
      return [Number.isFinite(parsed) ? String(parsed) : '0', BerryOrder.ATOMIC];
    };
    this.forBlock.text = (block) => [this.quote_(block.getFieldValue('TEXT') ?? ''), BerryOrder.ATOMIC];
    this.forBlock.variables_get = (block) => [
      this.getVariableName(block.getFieldValue('VAR')),
      BerryOrder.ATOMIC,
    ];
    this.forBlock.variables_set = (block) => {
      const name = this.getVariableName(block.getFieldValue('VAR'));
      return `${name} = ${value(this, block, 'VALUE')}\n`;
    };
    this.forBlock.math_change = (block) => {
      const name = this.getVariableName(block.getFieldValue('VAR'));
      return `${name} += ${value(this, block, 'DELTA', '0')}\n`;
    };
    this.forBlock.logic_negate = (block) => [
      `not ${value(this, block, 'BOOL', 'false', BerryOrder.UNARY)}`,
      BerryOrder.UNARY,
    ];
    this.forBlock.logic_compare = (block) => {
      const operators: Record<string, string> = {
        EQ: '==',
        NEQ: '!=',
        LT: '<',
        LTE: '<=',
        GT: '>',
        GTE: '>=',
      };
      const operator = operators[block.getFieldValue('OP')] ?? '==';
      const left = value(this, block, 'A', 'nil', BerryOrder.RELATIONAL);
      const right = value(this, block, 'B', 'nil', BerryOrder.RELATIONAL);
      return [`${left} ${operator} ${right}`, BerryOrder.RELATIONAL];
    };
    this.forBlock.logic_operation = (block) => {
      const operator = block.getFieldValue('OP') === 'AND' ? 'and' : 'or';
      const order = operator === 'and' ? BerryOrder.AND : BerryOrder.OR;
      return [
        `${value(this, block, 'A', 'false', order)} ${operator} ${value(this, block, 'B', 'false', order)}`,
        order,
      ];
    };
    this.forBlock.math_arithmetic = (block) => {
      if (block.getFieldValue('OP') === 'POWER') {
        this.definitions_.import_math = 'import math';
        const left = value(this, block, 'A', '0');
        const right = value(this, block, 'B', '0');
        return [`math.pow(${left}, ${right})`, BerryOrder.MEMBER];
      }
      const operators: Record<string, [string, BerryOrder]> = {
        ADD: ['+', BerryOrder.ADDITIVE],
        MINUS: ['-', BerryOrder.ADDITIVE],
        MULTIPLY: ['*', BerryOrder.MULTIPLICATIVE],
        DIVIDE: ['/', BerryOrder.MULTIPLICATIVE],
      };
      const [operator, order] = operators[block.getFieldValue('OP')] ?? ['+', BerryOrder.ADDITIVE];
      return [
        `${value(this, block, 'A', '0', order)} ${operator} ${value(this, block, 'B', '0', order)}`,
        order,
      ];
    };
    this.forBlock.controls_if = (block) => {
      let code = '';
      let index = 0;
      while (block.getInput(`IF${index}`)) {
        const keyword = index === 0 ? 'if' : 'elif';
        code += `${keyword} ${value(this, block, `IF${index}`, 'false')}\n`;
        code += body(this, block, `DO${index}`);
        index += 1;
      }
      if (block.getInput('ELSE')) code += `else\n${body(this, block, 'ELSE')}`;
      return `${code}end\n`;
    };
    this.forBlock.controls_whileUntil = (block) => {
      const condition = value(this, block, 'BOOL', 'false');
      const test = block.getFieldValue('MODE') === 'UNTIL' ? `not (${condition})` : condition;
      const branch = this.addLoopTrap(body(this, block, 'DO'), block);
      return `while ${test}\n${branch}end\n`;
    };
  }

  private installDomainGenerators(): void {
    this.forBlock.mini_sps_task = (block) => {
      const name = identifier(block.getFieldValue('NAME') ?? '', 'steuerung');
      const interval = Math.max(10, numberField(block, 'INTERVAL', 100));
      return [
        `def ${name}_init()\n`,
        body(this, block, 'INIT'),
        'end\n\n',
        `def ${name}_cycle()\n`,
        body(this, block, 'LOOP'),
        'end\n\n',
        `${name}_init()\n`,
        `sps.every(${interval}, ${name}_cycle)\n`,
      ].join('');
    };
    this.forBlock.sps_wait_ms = (block) =>
      `sps.wait(${value(this, block, 'DURATION', '0')})\n`;
    this.forBlock.sps_digital_input = (block) => [
      `sps.input(${this.quote_(block.getFieldValue('CHANNEL') ?? '')})`,
      BerryOrder.MEMBER,
    ];
    this.forBlock.sps_digital_output = (block) =>
      `sps.output(${this.quote_(block.getFieldValue('CHANNEL') ?? '')}, ${value(this, block, 'VALUE', 'false')})\n`;
    this.forBlock.escalation_rule = (block) => {
      const id = this.quote_(block.id);
      const condition = value(this, block, 'CONDITION', 'false');
      const level = this.quote_(block.getFieldValue('LEVEL') ?? 'warning');
      const message = value(this, block, 'MESSAGE', '""');
      const cooldown = Math.max(0, numberField(block, 'COOLDOWN', 60));
      return `if escalation.raise_if(${id}, ${condition}, ${level}, ${message}, ${cooldown})\n${body(this, block, 'ON_TRIGGER')}end\n`;
    };
    this.forBlock.signal_set = (block) =>
      `signal.set(${this.quote_(block.getFieldValue('SIGNAL') ?? '')}, ${this.quote_(block.getFieldValue('STATE') ?? 'off')})\n`;
    this.forBlock.monitor_value = (block) =>
      `monitor.record(${this.quote_(block.getFieldValue('METRIC') ?? '')}, ${value(this, block, 'VALUE')}, ${this.quote_(block.getFieldValue('UNIT') ?? '')})\n`;
    this.forBlock.od_read = (block) => [
      `od.read(${odIndex(block.getFieldValue('INDEX'))}, ${numberField(block, 'SUBINDEX')})`,
      BerryOrder.MEMBER,
    ];
    this.forBlock.od_write = (block) =>
      `od.write(${odIndex(block.getFieldValue('INDEX'))}, ${numberField(block, 'SUBINDEX')}, ${value(this, block, 'VALUE')})\n`;
    this.forBlock.canopen_sdo_read = (block) => [
      `canopen.sdo_read(${numberField(block, 'NODE', 1)}, ${odIndex(block.getFieldValue('INDEX'))}, ${numberField(block, 'SUBINDEX')})`,
      BerryOrder.MEMBER,
    ];
    this.forBlock.canopen_sdo_write = (block) =>
      `canopen.sdo_write(${numberField(block, 'NODE', 1)}, ${odIndex(block.getFieldValue('INDEX'))}, ${numberField(block, 'SUBINDEX')}, ${value(this, block, 'VALUE')})\n`;
    this.forBlock.canopen_nmt = (block) =>
      `canopen.nmt(${numberField(block, 'NODE', 1)}, ${this.quote_(block.getFieldValue('COMMAND') ?? 'start')})\n`;
    this.forBlock.lvgl_set_text = (block) =>
      `ui.set_text(${this.quote_(block.getFieldValue('WIDGET') ?? '')}, ${value(this, block, 'TEXT', '""')})\n`;
    this.forBlock.lvgl_set_visible = (block) =>
      `ui.set_visible(${this.quote_(block.getFieldValue('WIDGET') ?? '')}, ${value(this, block, 'VISIBLE', 'false')})\n`;
    this.forBlock.lvgl_set_color = (block) =>
      `ui.set_color(${this.quote_(block.getFieldValue('WIDGET') ?? '')}, ${this.quote_(block.getFieldValue('COLOR') ?? 'gray')})\n`;
  }
}

export const berryGenerator = new BerryGenerator();
